# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Demo - DIRCTL

description: |
  This workflow demonstrates how to use the Dir CLI in GitHub Actions.

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup dirctl
        uses: agntcy/dir/.github/actions/setup-dirctl@main

      - name: Check dirctl version
        run: |
          echo "Running version command"
          dirctl version

      # Continue developer flows such as:
      # - Push
      # - Verify
      # - Publish
      # - Search
      # - Discover
