# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Build

on:
  workflow_call:
    inputs:
      image_repo:
        required: true
        type: string
        description: "Image repo to use."
      image_tag:
        required: true
        type: string
        description: "Image tag to use."
      push:
        required: false
        type: boolean
        default: false
        description: "Whether to push the image to the registry."

jobs:
  prepare:
    name: Prepare
    outputs:
      targets: ${{ steps.targets.outputs.targets }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: List targets
        id: targets
        uses: docker/bake-action/subaction/list-targets@a4d7f0b5b91c14a296d792d4ec53a9db17f02e67 # v5.5.0

  image:
    name: Image
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Login to ghcr.io
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: notused
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Cache Docker layers
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/Dockerfile*', '**/go.sum', 'docker-bake.hcl') }}
          restore-keys: |
            buildx-${{ runner.os }}-${{ matrix.target }}-${{ github.ref_name }}-
            buildx-${{ runner.os }}-${{ matrix.target }}-main-
            buildx-${{ runner.os }}-${{ matrix.target }}-

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: |
            ${{ inputs.image_repo }}/${{ matrix.target }},enable=true
          tags: |
            type=raw,value=${{ inputs.image_tag }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Create cache and artifacts directories
        run: |
          mkdir -p /tmp/.buildx-cache
          mkdir /tmp/artifacts

      - name: Build and push
        if: ${{ inputs.push }}
        uses: docker/bake-action@a4d7f0b5b91c14a296d792d4ec53a9db17f02e67 # v5.5.0
        with:
          push: true
          provenance: false
          files: |
            ./docker-bake.hcl
            ${{ steps.metadata.outputs.bake-file }}
          targets: ${{ matrix.target }}
          set: |
            *.platform=linux/amd64,linux/arm64
            *.output=type=registry
            *.cache-to=type=local,dest=/tmp/.buildx-cache,mode=max
            *.cache-from=type=local,src=/tmp/.buildx-cache
        env:
          IMAGE_REPO: ${{ inputs.image_repo }}
          IMAGE_TAG: ${{ inputs.image_tag }}

      - name: Build and load
        if: ${{ !inputs.push }}
        uses: docker/bake-action@a4d7f0b5b91c14a296d792d4ec53a9db17f02e67 # v5.5.0
        with:
          provenance: false
          files: |
            ./docker-bake.hcl
            ${{ steps.metadata.outputs.bake-file }}
          targets: ${{ matrix.target }}
          set: |
            *.platform=linux/amd64
            *.output=type=docker,dest=/tmp/artifacts/${{ matrix.target }}.tar
            *.cache-to=type=local,dest=/tmp/.buildx-cache,mode=max
            *.cache-from=type=local,src=/tmp/.buildx-cache
        env:
          IMAGE_REPO: ${{ inputs.image_repo }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          DOCKER_BUILD_RECORD_UPLOAD: false

      - name: Upload artifacts
        if: ${{ !inputs.push }}
        uses: actions/upload-artifact@v4.6.1
        with:
          name: ${{ matrix.target }}
          path: /tmp/artifacts/${{ matrix.target }}.tar
          retention-days: 1
